title: "Idelfonso Nogueira"
author: "Idelfonso Nogueira"
description: "Idelfonso Nogueira â€“ Chemical Engineering, Process Systems Engineering and AI Researcher"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home", icon: home}
  - {file: "Resume.md", title: "CV", icon: file}
  - {file: "Publications.md", title: "Publications", icon: atom}
  - {file: "Orientations.md", title: "Supervision", icon: university}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:idelfonso.nogueira@gmail.com"}
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
